name: responsive_util
description: A wrapper that provides draggable manipulation of a widget's size to test it's responsive design.
version: 0.1.0
homepage: https://github.com/hawkinsjb1/responsive_util

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: