name: responsive_util
description: A Flutter widget that allows drag resizing of its child's bounds to easily test responsive design.

publish_to: https://pub.dev/packages/responsive_util

version: 0.4.1
homepage: https://github.com/hawkinsjb1/responsive_util

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any

flutter: